# Generated by Django 2.1.1 on 2018-09-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cal', models.IntegerField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField()),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user')),
            ],
            options={
                'db_table': 'sport_sportitem',
            },
        ),
        migrations.CreateModel(
            name='sportrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cal', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField()),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user')),
                ('sportid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sportitem')),
            ],
            options={
                'db_table': 'sport_sportrecord',
            },
        ),
        migrations.CreateModel(
            name='weightrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sportitem')),
            ],
            options={
                'db_table': 'sport_weightrecord',
            },
        ),
    ]
