# Generated by Django 2.1.1 on 2018-09-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportrecord',
            name='state',
        ),
        migrations.RemoveField(
            model_name='weightrecord',
            name='userid',
        ),
        migrations.AlterField(
            model_name='sportitem',
            name='cal',
            field=models.IntegerField(verbose_name='卡洛里(每小時/每公斤)'),
        ),
        migrations.AlterField(
            model_name='sportitem',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportitem',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportitem',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sportitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='運動項目'),
        ),
        migrations.AlterField(
            model_name='sportrecord',
            name='cal',
            field=models.IntegerField(verbose_name='運動消耗卡洛里calorie'),
        ),
        migrations.AlterField(
            model_name='sportrecord',
            name='duration',
            field=models.IntegerField(verbose_name='運動持續時間(分鐘)'),
        ),
        migrations.AlterField(
            model_name='sportrecord',
            name='sportid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sportitem', verbose_name='運動項目'),
        ),
        migrations.AlterField(
            model_name='sportrecord',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='體重'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='limit.user', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='體重(公斤)'),
        ),
    ]
